//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamodels1
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public string class_name { get; set; }
        public int id { get; set; }
        public int seat { get; set; }
        public int level_id { get; set; }
    
        public virtual Level Level { get; set; }
    }
}
