//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamodels1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.classes = new HashSet<@class>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public string leval_name { get; set; }
        public int level_id { get; set; }
    
        public virtual ICollection<@class> classes { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
