//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datamodels1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public string student_name { get; set; }
        public int studentid { get; set; }
        public string Email { get; set; }
        public Nullable<int> mobile { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string username { get; set; }
        public Nullable<int> password { get; set; }
        public Nullable<int> comfirm_password { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> level_id { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> idi { get; set; }
        public string student_data { get; set; }
        public Nullable<int> attendanceid { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Attendance Attendance { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
